### ISSUE TITLE
Update CBot documentation

### ISSUE THREAD

**Issue by krzys-h** [colobot/colobot#525]
The following new things need to be documented in-game:
* [x] build(cat);
* [x] object.factory(cat, program); *(program is a string and can be either public function name, program filename or raw program code)*
* [x] object.research(research); + all ResearchXXXX constants *(yes, this works for AutoLab too)*
* [x] object.takeoff();
* [x] object.destroy(); *hidden from function list until Destroyer is officially added*
* [x] object.busy();
* [x] Destroyer *(I know, this is not CBot. Hidden from category list until officially added)*
* [x] aim(y, x) *addition of the second argument*
* [x] atan2(y, x)
* [x] floor(x)
* [x] ceil(x)
* [x] round(x)
* [x] trunc(x)
* [x] flatspace(center, flatmin, rmin, rmax, dist) *like space(), but makes sure there is at least flatmin flat space for building at the returned position*
* [x] canbuild(type)
* [x] canresearch(research) *(see #524)*
* [x] researched(research) *(see #524)*
* [x] buildingenabled(type) *(see #524)*
* [x] search(type, pos) *this is from one of the CeeBots, might be useful sometimes*
* [x] arrays to radar() and search()
* [x] Any to radar() and search()
* [x] FilterXXXX to radar()
* [x] object.team
* [x] object.velocity
* [x] pendown(color=Black, width=1)
* [x] penup()
* [x] pencolor(color)
* [x] penwidth(width)
* [x] Some page explaining basics of Colobot production line. This will be liked in code battle levels and should learn user about elements of production chain needed e.g. to make a robot, even if somebody never played the main missions. Something like this, probably as an image with an explanation of each element:
```
                                   +==> BotFactory ===========================> some robot
                                  /          ^ use                              ^
                                 / build+use  \===========\                    /
                                /                         \                   /
TitaniumOre => Converter => Titanium => ResearchCenter => some research      /
                   ^           |\   build  ^ use                            /
                   |           | \         \=========\                     /
                   |  build    |  \build+use          \                   /
                   +===========+   +==> PowerPlant => PowerCell =========+
```
* [x] switch

This is all I remember. Feel free to remind me if I forgot anything.

**Comment by MrSimbax** [comment]
I've just noticed that there is no documentation of mathematical functions (e.g. sin, rand).

**Comment by MrSimbax** [comment]
Oh, wait, there are, but in a place I wouldn't have think of...

**Comment by MrSimbax** [comment]
Is Scribbler officially added? Don't know if the penX functions should be hidden or not...

**Comment by krzys-h** [comment]
Scribbler is not officially added, but penXXXX() functions work on any robot are useful for debugging

**Comment by MrSimbax** [comment]
And they will be working on any robot always? I mean, it won't be changed?

**Comment by krzys-h** [comment]
I don't think so. We wanted to add more of such debugging features, why would we remove them?

**Comment by MrSimbax** [comment]
I don't know. But it makes a little difference in describing them as only for Scribbler and as for all bots :P

**Comment by MrSimbax** [comment]
How do the filters work? It seems like they don't work at all for me... i.e. they have no effect whatsoever.

**Comment by krzys-h** [comment]
Something like this: ```radar(Any, 0, 360, 0, 1000, 1, FilterEnemy);```

**Comment by MrSimbax** [comment]
Ok, I know what I did wrong. So FilterEnemy searches only for aliens etc.?

**Comment by krzys-h** [comment]
FilterEnemy detects any objects on other team than what the robot executing has. It doesn't detect neutral objects.
Basically: this.team != other.team && other.team != 0

**Comment by MrSimbax** [comment]
Can more than one filter be used?

**Comment by krzys-h** [comment]
Yes, you can use bitwise OR. You can also put team ID instead of filter. Refer to the forum post about code battles for details.

**Comment by MrSimbax** [comment]
Wow, I didn't know there is bitwise OR operator in CBOT :+1: I'm gonna need to modify the docs then...

**Comment by MrSimbax** [comment]
`switch` is not documented.

**Comment by MrSimbax** [comment]
Everything is done for now. I'm closing this issue, but we may reopen it every time there is something new in CBOT.
